# Generated by Django 2.1.7 on 2019-07-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Job Image'),
        ),
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.URLField(verbose_name='Job Link'),
        ),
    ]
