# Generated by Django 2.1.7 on 2019-07-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jumbotron_Text', models.TextField(max_length=200)),
                ('statement', models.TextField(max_length=300)),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('postal', models.IntegerField(max_length=6)),
                ('country', models.CharField(max_length=30)),
                ('keywords', models.CharField(max_length=400)),
                ('meta_description', models.TextField(max_length=160)),
            ],
        ),
    ]
