# Generated by Django 2.1.7 on 2019-07-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='Jumbotron_Text',
            field=models.TextField(max_length=200, verbose_name='Jumbotron Text'),
        ),
        migrations.AlterField(
            model_name='home',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='home',
            name='company_name',
            field=models.CharField(max_length=100, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='home',
            name='country',
            field=models.CharField(max_length=30, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='home',
            name='keywords',
            field=models.CharField(max_length=400, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='home',
            name='meta_description',
            field=models.TextField(max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='home',
            name='postal',
            field=models.IntegerField(verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='home',
            name='state',
            field=models.CharField(max_length=20, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='home',
            name='statement',
            field=models.TextField(max_length=300, verbose_name='Statement'),
        ),
    ]
