# Generated by Django 2.1.7 on 2019-07-05 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190706_0004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
