# Generated by Django 2.1.7 on 2019-07-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190706_0724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='Jumbotron_Text',
            new_name='jumbotron_text',
        ),
    ]
